// r2m2.h - automatically generated by gen_includes.py
// Copyright (C) 2016 Guillaume Valadon <guillaume@valadon.net>

// CFFI does not support all C directive such as #include, therefore some
// radare2 structures must be included in r2m2

#define R2M2_ARCH_BITS 32 // GV: this sould not be hardcoded

typedef struct r_asm_op_t_r2m2 {
 int size;
 int payload;
 unsigned char buf[256];
 char buf_asm[256];
 char buf_hex[256];
} RAsmOp_r2m2;

typedef void (*RListFree)(void *ptr);typedef struct r_list_iter_t_r2m2 {
 void *data;
 struct r_list_iter_t *n, *p;
} RListIter_r2m2;typedef struct r_list_t_r2m2 {
 RListIter_r2m2 *head;
 RListIter_r2m2 *tail;
 RListFree free;
} RList_r2m2;
typedef struct r_reg_item_t_r2m2 {
 char *name;
 int type;
 int size;
 int offset;
 int packed_size;
 
_Bool 
     is_float;
 char *flags;
 int index;
} RRegItem_r2m2;
typedef struct {
 int len;
 char *ptr;
 int ptrlen;
 char buf[64];
} RStrBuf_r2m2;
typedef struct r_anal_var_t_r2m2 {
 char *name;
 char *type;
 char kind;
 unsigned long long addr;
 unsigned long long eaddr;
 int size;
 int delta;
 int scope;
 RList_r2m2 *accesses;
 RList_r2m2 *stores;
} RAnalVar_r2m2;
typedef struct r_anal_value_t_r2m2 {
 int absolute;
 int memref;
 unsigned long long base ;
 long long delta;
 long long imm;
 int mul;
 unsigned short sel;
 RRegItem_r2m2 *reg;
 RRegItem_r2m2 *regdelta;
} RAnalValue_r2m2;
typedef struct r_anal_switch_obj_t_r2m2 {
 unsigned long long addr;
 unsigned long long min_val;
 unsigned long long def_val;
 unsigned long long max_val;
 RList_r2m2 *cases;
} RAnalSwitchOp_r2m2;
typedef struct r_anal_op_t_r2m2 {
 char *mnemonic;
 unsigned long long addr;
 unsigned long long type;
 unsigned long long prefix;
 unsigned long long type2;
 int group;
 int stackop;
 int cond;
 int size;
 int nopcode;
 int cycles;
 int failcycles;
 int family;
 
_Bool 
     eob;
 int delay;
 unsigned long long jump;
 unsigned long long fail;
 long long ptr;
 unsigned long long val;
 int ptrsize;
 long long stackptr;
 int refptr;
 RAnalVar_r2m2 *var;
 RAnalValue_r2m2 *src[3];
 RAnalValue_r2m2 *dst;
 struct r_anal_op_t *next;
 RStrBuf_r2m2 esil;
 const char *reg;
 RAnalSwitchOp_r2m2 *switch_op;
} RAnalOp_r2m2;
